# Generated by Django 5.2.5 on 2025-09-28 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='duration_minutes',
        ),
        migrations.AddField(
            model_name='service',
            name='duration_days',
            field=models.PositiveIntegerField(default=3, help_text='Number of days to complete the service'),
            preserve_default=False,
        ),
    ]
