# Generated by Django 5.2.5 on 2025-10-02 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_change_service_duration_to_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='duration_days',
            field=models.PositiveIntegerField(help_text='Duration of service in days'),
        ),
    ]
