# Generated by Django 5.2.5 on 2025-10-02 14:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_alter_service_duration_days'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='scheduled_time',
            new_name='delivery_date',
        ),
        migrations.AddField(
            model_name='booking',
            name='pickup_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('pickup_ready', 'Ready for Pickup'), ('picked_up', 'Picked Up'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
