# Generated by Django 5.2.5 on 2025-11-06 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_booking_stripe_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tailorprofile',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Profile photo (shop front, workspace, etc.)', null=True, upload_to='tailor_profiles/'),
        ),
        migrations.CreateModel(
            name='ReviewImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='review_images/')),
                ('alt_text', models.CharField(blank=True, help_text='Alternative text for accessibility', max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='marketplace.review')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='service_images/')),
                ('alt_text', models.CharField(blank=True, help_text='Alternative text for accessibility', max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display order (0 = first)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='marketplace.service')),
            ],
            options={
                'ordering': ['order', 'uploaded_at'],
                'unique_together': {('service', 'order')},
            },
        ),
    ]
